// GENERATED by tools/test-homework.mjs --write from the reference solutions. Do not edit.
// The numbers a correct HW4 reproduces, the same as the homework page and the WebGL runner.
using UnityEngine;

namespace CSS551.HW04
{
    public struct Check
    {
        public string Id, Label; public int Points; public double Tol; public double[] Want;
        public Check(string id, string label, int points, double tol, double[] want) { Id = id; Label = label; Points = points; Tol = tol; Want = want; }
    }

    public static class Expected
    {
        public static readonly Check[] Checks = {
            new Check("V", "viewMatrix: all 16 entries of V", 20, 0.002, new double[] { 0.81915406414, -0.196169815907, 0.538984250725, 0.0, 0.0, 0.939695090775, 0.34201335701, 0.0, -0.573573551694, -0.280161631385, 0.769755052661, 0.0, -4.4408920985e-16, -0.469847545388, -7.17102568634, 1.0 }),
            new Check("P", "perspectiveMatrix(45°, 16:9, 1, 8): all 16 entries", 15, 0.002, new double[] { 1.35799512883, 0.0, 0.0, 0.0, 0.0, 2.41421356237, 0.0, 0.0, 0.0, 0.0, -1.28571428571, -1.0, 0.0, 0.0, -2.28571428571, 0.0 }),
            new Check("pixel", "worldToPixel: object point (0.5, 0.5, 0.5) to pixel x, y and NDC depth", 20, 0.05, new double[] { 702.505054, 320.86392268, 0.924050878292 }),
            new Check("baryIn", "barycentric at the center of pixel (5, 6)", 12, 0.002, new double[] { 0.305195283543, 0.258985320636, 0.43581939582 }),
            new Check("baryOut", "barycentric at the center of pixel (1, 9): outside, one weight negative", 8, 0.002, new double[] { 0.2992371459, -0.388659209033, 1.08942206313 }),
            new Check("count", "rasterize at 12 × 12: number of covered pixels", 15, 0.0, new double[] { 28.0 }),
            new Check("count64", "rasterize at 64 × 64: number of covered pixels", 10, 0.0, new double[] { 846.0 }),
        };
    }
}
