// GENERATED by tools/test-homework.mjs --write. Do not edit.
// The published inputs of HW4 (the same as lib/skeletons/checks.js).
using UnityEngine;

namespace CSS551.HW04
{
    public static class Inputs
    {
        public static readonly Vector3 eye = new Vector3(3.7729f, 2.8941f, 5.3883f);
        public static readonly Vector3 at = new Vector3(0f, 0.5f, 0f);
        public static readonly Vector3 up = new Vector3(0f, 1f, 0f);
        public static readonly float fov = 45f;
        public static readonly float width = 1280f;
        public static readonly float height = 720f;
        public static readonly float near = 1f;
        public static readonly float far = 8f;
        public static readonly float model_ry = 30f;
        public static readonly Vector3 model_t = new Vector3(0f, 0.5f, 0f);
        public static readonly Vector3 objectPoint = new Vector3(0.5f, 0.5f, 0.5f);
        public static readonly Vector2[] tri = { new Vector2(0.242102f, 0.143041f), new Vector2(0.876839f, 0.478762f), new Vector2(0.361059f, 0.858197f) };
        public static readonly float res = 12f;
        public static readonly Vector2 pixelIn = new Vector2(5f, 6f);
        public static readonly Vector2 pixelOut = new Vector2(1f, 9f);
    }
}
