// GENERATED by tools/test-homework.mjs --write from the reference solutions. Do not edit.
// The numbers a correct HW6 reproduces, the same as the homework page and the WebGL runner.
using UnityEngine;

namespace CSS551.HW06
{
    public struct Check
    {
        public string Id, Label; public int Points; public double Tol; public double[] Want;
        public Check(string id, string label, int points, double tol, double[] want) { Id = id; Label = label; Points = points; Tol = tol; Want = want; }
    }

    public static class Expected
    {
        public static readonly Check[] Checks = {
            new Check("ray", "cameraRay through pixel (89, 62) of 150 × 150: direction", 12, 0.001, new double[] { -0.371968114866, -0.369566560481, -0.851504714548 }),
            new Check("tSphere", "hitSphere: nearest t on the radius-1.2 sphere", 12, 0.001, new double[] { 6.22811754315 }),
            new Check("tri", "hitTriangle (Möller–Trumbore): t, u, v", 12, 0.001, new double[] { 1.0, 0.25, 0.25 }),
            new Check("triMiss", "hitTriangle: the ray from (1.5, 1.5, 1) misses (null) while the one from (0.5, 0.5, 1) hits", 6, 0.0, new double[] { 1.0, 1.0 }),
            new Check("reflect", "reflect (0.6, −0.8, 0) about (0, 1, 0)", 6, 0.000001, new double[] { 0.6, 0.8, 0.0 }),
            new Check("lit", "Cornell box, pixel (24, 63): lit floor", 12, 0.002, new double[] { 0.693316101435, 0.693316101435, 0.693316101435 }),
            new Check("shadow", "Cornell box, pixel (36, 66): floor in the diffuse sphere’s shadow", 14, 0.002, new double[] { 0.08, 0.08, 0.08 }),
            new Check("mirror", "Cornell box, pixel (54, 56): the red wall seen in the mirror sphere", 14, 0.002, new double[] { 0.455996340601, 0.0911992681202, 0.0729594144962 }),
            new Check("wall", "Cornell box, pixel (6, 30): the red wall", 12, 0.002, new double[] { 0.583402417605, 0.116680483521, 0.0933443868168 }),
        };
    }

    // The Cornell box of the checks (generated from lib/skeletons/checks.js CORNELL).
    public static class Cornell
    {
        public const float Ka = 0.1f;
        public const int MaxDepth = 3;
        public static readonly Vector3 Light = new Vector3(0f, 1.9f, 0f);
        public static readonly Sphere[] Spheres = {
            new Sphere(new Vector3(-0.4f, 0.35f, -0.3f), 0.35f, Material.Diffuse(new Vector3(0.8f, 0.8f, 0.8f))),
            new Sphere(new Vector3(0.45f, 0.4f, 0.2f), 0.4f, Material.Mirror(0.9f)),
        };
        public static readonly Triangle[] Triangles = {
            new Triangle(new Vector3(-1f, 0f, 3f), new Vector3(1f, 0f, 3f), new Vector3(1f, 0f, -1f), Material.Diffuse(new Vector3(0.8f, 0.8f, 0.8f))),
            new Triangle(new Vector3(-1f, 0f, 3f), new Vector3(1f, 0f, -1f), new Vector3(-1f, 0f, -1f), Material.Diffuse(new Vector3(0.8f, 0.8f, 0.8f))),
            new Triangle(new Vector3(-1f, 2f, 3f), new Vector3(-1f, 2f, -1f), new Vector3(1f, 2f, -1f), Material.Diffuse(new Vector3(0.8f, 0.8f, 0.8f))),
            new Triangle(new Vector3(-1f, 2f, 3f), new Vector3(1f, 2f, -1f), new Vector3(1f, 2f, 3f), Material.Diffuse(new Vector3(0.8f, 0.8f, 0.8f))),
            new Triangle(new Vector3(-1f, 0f, -1f), new Vector3(1f, 0f, -1f), new Vector3(1f, 2f, -1f), Material.Diffuse(new Vector3(0.8f, 0.8f, 0.8f))),
            new Triangle(new Vector3(-1f, 0f, -1f), new Vector3(1f, 2f, -1f), new Vector3(-1f, 2f, -1f), Material.Diffuse(new Vector3(0.8f, 0.8f, 0.8f))),
            new Triangle(new Vector3(1f, 0f, 3f), new Vector3(-1f, 0f, 3f), new Vector3(-1f, 2f, 3f), Material.Diffuse(new Vector3(0.8f, 0.8f, 0.8f))),
            new Triangle(new Vector3(1f, 0f, 3f), new Vector3(-1f, 2f, 3f), new Vector3(1f, 2f, 3f), Material.Diffuse(new Vector3(0.8f, 0.8f, 0.8f))),
            new Triangle(new Vector3(-1f, 0f, 3f), new Vector3(-1f, 0f, -1f), new Vector3(-1f, 2f, -1f), Material.Diffuse(new Vector3(0.75f, 0.15f, 0.12f))),
            new Triangle(new Vector3(-1f, 0f, 3f), new Vector3(-1f, 2f, -1f), new Vector3(-1f, 2f, 3f), Material.Diffuse(new Vector3(0.75f, 0.15f, 0.12f))),
            new Triangle(new Vector3(1f, 0f, -1f), new Vector3(1f, 0f, 3f), new Vector3(1f, 2f, 3f), Material.Diffuse(new Vector3(0.15f, 0.6f, 0.2f))),
            new Triangle(new Vector3(1f, 0f, -1f), new Vector3(1f, 2f, 3f), new Vector3(1f, 2f, -1f), Material.Diffuse(new Vector3(0.15f, 0.6f, 0.2f))),
        };
    }
}
