// GENERATED by tools/test-homework.mjs --write. Do not edit.
// The published inputs of HW6 (the same as lib/skeletons/checks.js).
using UnityEngine;

namespace CSS551.HW06
{
    public static class Inputs
    {
        public static readonly Vector3 cam_eye = new Vector3(3f, 3f, 6f);
        public static readonly Vector3 cam_at = new Vector3(0f, 0f, 0f);
        public static readonly Vector3 cam_up = new Vector3(0f, 1f, 0f);
        public static readonly float cam_fov = 28f;
        public static readonly float size = 150f;
        public static readonly Vector2 pixel = new Vector2(89f, 62f);
        public static readonly Vector3 sphere_c = new Vector3(0f, 0f, 0f);
        public static readonly float sphere_r = 1.2f;
        public static readonly Vector3 tri_a = new Vector3(0f, 0f, 0f);
        public static readonly Vector3 tri_b = new Vector3(2f, 0f, 0f);
        public static readonly Vector3 tri_c = new Vector3(0f, 2f, 0f);
        public static readonly Vector3 tri_o = new Vector3(0.5f, 0.5f, 1f);
        public static readonly Vector3 tri_d = new Vector3(0f, 0f, -1f);
        public static readonly Vector3 tri_missO = new Vector3(1.5f, 1.5f, 1f);
        public static readonly Vector3 reflect_d = new Vector3(0.6f, -0.8f, 0f);
        public static readonly Vector3 reflect_n = new Vector3(0f, 1f, 0f);
        public static readonly Vector3 cornell_cam_eye = new Vector3(0f, 1f, 2.8f);
        public static readonly Vector3 cornell_cam_at = new Vector3(0f, 1f, 0f);
        public static readonly Vector3 cornell_cam_up = new Vector3(0f, 1f, 0f);
        public static readonly float cornell_cam_fov = 40f;
        public static readonly float cornell_width = 96f;
        public static readonly float cornell_height = 72f;
        public static readonly Vector2 cornell_lit = new Vector2(24f, 63f);
        public static readonly Vector2 cornell_shadow = new Vector2(36f, 66f);
        public static readonly Vector2 cornell_mirror = new Vector2(54f, 56f);
        public static readonly Vector2 cornell_wall = new Vector2(6f, 30f);
    }
}
