// site-data.js: the verified content behind the course site's extras (icon facts, fun facts,
// quotes, comics). Plain data, no imports. Every entry carries a source; course numbers come from
// the course text and its numbers JSON files, computed values are noted as computed.
// Checked 2026-09-29. Disputed stories are phrased as disputed.

export const ICON_FACTS = {
  teapot: [
    { t: "Martin Newell modeled the teapot at the University of Utah in 1974 or 1975 (sources differ), sketching his own Melitta teapot on graph paper and entering its outline as Bézier control points.",
      src: "Computer History Museum, object X398.84 (1974) https://www.computerhistory.org/collections/catalog/X398.84; University of Utah https://graphics.cs.utah.edu/history/utah_teapot.php; https://en.wikipedia.org/wiki/Utah_teapot" },
    { t: "The real teapot is about a third taller than the famous computer model. The model was squashed to three quarters of its height early on; one story blames non-square frame-buffer pixels, another says Jim Blinn simply preferred the squatter shape.",
      src: "https://en.wikipedia.org/wiki/Utah_teapot; https://geometrian.com/resources/utah_teapot/" },
    { t: "The original teapot is in the Computer History Museum in Mountain View, California.",
      src: "https://commons.wikimedia.org/wiki/File:Original_Utah_Teapot_-_Computer_History_Museums.jpg" },
    { t: "Newell's original data describes the teapot with 28 bicubic Bézier patches and no bottom; the four patches of the bottom, making 32, were added later (Frank Crow's 1987 version).",
      src: "University of Utah, The Utah Teapot https://graphics.cs.utah.edu/history/utah_teapot.php" },
    { t: "The teapot is a standard primitive in OpenGL's GLUT, in Direct3D's old utility library and in three.js (TeapotGeometry, which this course's demos use).",
      src: "lib/core/models.js; lib/vendor/TeapotGeometry.js" },
  ],
  bunny: [
    { t: "The Stanford bunny was scanned in 1994 by Greg Turk and Marc Levoy from a terra-cotta (clay) rabbit, using a laser range scanner and several overlapping scans merged into one surface.",
      src: "Stanford 3D Scanning Repository, https://graphics.stanford.edu/data/3Dscanrep/; Greg Turk, The Stanford Bunny https://faculty.cc.gatech.edu/~turk/bunny/bunny.html" },
    { t: "The full-resolution bunny this course loads has 35,947 vertices and 69,451 triangles.",
      src: "lib/assets/models/CREDITS.md (bun_zipper.ply)" },
    { t: "The scanned bunny has holes in its base where the scanner could not see, which is why it is often shown sitting on a floor.",
      src: "Stanford 3D Scanning Repository" },
    { t: "This course bakes the bunny into four levels of detail and a progressive-mesh stream, so the same scan serves the LOD, simplification and lighting demos.",
      src: "lib/assets/models/CREDITS.md" },
  ],
  dragon: [
    { t: "The Stanford dragon was scanned in 1996 and is the bunny's larger sibling in the same Stanford 3D Scanning Repository.",
      src: "https://graphics.stanford.edu/data/3Dscanrep/" },
    { t: "The dragon's thin horns, claws and scales make it a hard test for mesh simplification: a method that keeps them at a low triangle count is doing something right.",
      src: "course text, Polygonal Meshes (simplification)" },
    { t: "The same Stanford lab later scanned Michelangelo's David at 0.25 mm spacing into 2 billion polygons of raw data, 32 GB compressed.",
      src: "Levoy et al., The Digital Michelangelo Project, SIGGRAPH 2000, http://graphics.stanford.edu/papers/dmich-sig00/" },
    { t: "This course bakes the dragon into four levels of detail, like the bunny, for the mesh viewer and the LOD demo.",
      src: "lib/assets/models/CREDITS.md" },
  ],
  cornell: [
    { t: "The Cornell box first appeared in 1984, in Goral, Torrance, Greenberg and Battaile's radiosity paper at SIGGRAPH.",
      src: "Goral et al., Modeling the interaction of light between diffuse surfaces, SIGGRAPH 1984" },
    { t: "Cornell's lab built a real box and photographed it, so a rendering could be compared with measurements of the physical scene.",
      src: "https://www.graphics.cornell.edu/online/box/" },
    { t: "The red and green walls exist to show color bleeding: light bounced off a colored wall tints the white boxes next to it, which only global illumination reproduces.",
      src: "course text, Light Transport and PBR" },
    { t: "The course text renders its own Cornell box with a path tracer and measures how the noise falls as samples are added.",
      src: "course text, Ray Tracing and Global Illumination" },
  ],
  whitted: [
    { t: "Turner Whitted's 1980 paper, An Improved Illumination Model for Shaded Display, introduced recursive ray tracing with reflection, refraction and shadows.",
      src: "Whitted, CACM 23(6), 1980" },
    { t: "Whitted's famous image of spheres over a checkerboard took 74 minutes to render on a VAX-11/780, at 480 by 640 pixels.",
      src: "Whitted 1980, Section 4 (Results); https://www.cs.drexel.edu/~deb39/Classes/Papers/p343-whitted.pdf" },
    { t: "The same program also ran on a DEC PDP-11/45, which the paper says was nearly three times slower than the VAX; the pictures were displayed with 9 bits per pixel.",
      src: "Whitted 1980, Section 4 (Results); https://www.cs.drexel.edu/~deb39/Classes/Papers/p343-whitted.pdf" },
    { t: "A checkerboard under a mirror or glass sphere is still a standard test image, because its straight lines show every error in reflection and refraction at a glance.",
      src: "course text, Ray Tracing and Global Illumination" },
  ],
};

export const FACTS = [
  // history
  { topic: "history", t: "The term “computer graphics” was coined around 1960 at Boeing, by William Fetter working in Verne Hudson's group; sources credit both.", src: "https://en.wikipedia.org/wiki/William_Fetter" },
  { topic: "history", t: "Ivan Sutherland's Sketchpad (1963, MIT) was drawn with a light pen on a vector display and already had constraints, master drawings with instances, and zoom.", src: "Sutherland, Sketchpad, MIT PhD thesis, 1963" },
  { topic: "history", t: "The first SIGGRAPH conference was held in 1974 in Boulder, Colorado.", src: "https://www.siggraph.org/about/history/" },
  { topic: "history", t: "The University of Utah's program of the late 1960s and 1970s produced the founders of Pixar (Ed Catmull), Adobe (John Warnock) and Silicon Graphics (Jim Clark), and Alan Kay.", src: "course text, A History of Computer Graphics" },
  { topic: "history", t: "Ed Catmull and Fred Parke's 1972 short A Computer Animated Hand was added to the U.S. National Film Registry in 2011.", src: "Library of Congress, National Film Registry 2011" },
  { topic: "history", t: "Ed Catmull and Pat Hanrahan received the 2019 ACM Turing Award for fundamental contributions to 3D computer graphics.", src: "https://awards.acm.org/about/2019-turing" },
  // vectors
  { topic: "vectors", t: "Hamilton named the two parts of a quaternion the scalar and the vector part; the everyday words “scalar” and “vector” come from quaternions.", src: "https://en.wikipedia.org/wiki/Classical_Hamiltonian_quaternions" },
  { topic: "vectors", t: "Modern vector notation (dot, cross, the del operator) was developed independently by Josiah Willard Gibbs and Oliver Heaviside in the 1880s, partly as a simpler rival to quaternions.", src: "https://en.wikipedia.org/wiki/Vector_calculus" },
  { topic: "vectors", t: "A cross product with the familiar properties (bilinear, perpendicular to both inputs, length equal to the parallelogram's area) exists only in 3 and 7 dimensions.", src: "https://en.wikipedia.org/wiki/Seven-dimensional_cross_product" },
  { topic: "vectors", t: "A 3D dot product costs 3 multiplications and 2 additions; a cross product 6 multiplications and 3 subtractions. That is most of the arithmetic behind lighting.", src: "computed" },
  { topic: "vectors", t: "acos of a dot product loses precision for nearly parallel vectors: at 0.1°, the dot product differs from 1 only in the sixth decimal place. atan2 of the cross and dot products does not have this problem.", src: "course text, Vectors (pitfall)" },
  // rotation
  { topic: "rotation", t: "On 16 October 1843, William Rowan Hamilton carved i² = j² = k² = ijk = −1 into Broom Bridge in Dublin. The carving is gone; a plaque marks the spot, and mathematicians walk there every year.", src: "https://en.wikipedia.org/wiki/Broom_Bridge" },
  { topic: "rotation", t: "On Apollo 11, when Houston warned that Columbia was close to gimbal lock, Michael Collins replied: “How about sending me a fourth gimbal for Christmas?”", src: "Apollo 11 air-to-ground transcript, https://apollo11.spacelog.org/" },
  { topic: "rotation", t: "Olinde Rodrigues published his rotation formula in 1840, three years before Hamilton found quaternions.", src: "https://en.wikipedia.org/wiki/Rodrigues%27_rotation_formula" },
  { topic: "rotation", t: "There are 12 valid Euler angle orderings: 6 with three different axes (Tait-Bryan, like yaw-pitch-roll) and 6 that repeat the first axis (proper Euler, like z-x-z).", src: "https://en.wikipedia.org/wiki/Euler_angles" },
  { topic: "rotation", t: "A rotation matrix stores 9 numbers for 3 degrees of freedom; a unit quaternion stores 4. And q and −q are the same rotation.", src: "course text, Rotation" },
  { topic: "rotation", t: "Ken Shoemake brought quaternions and slerp to computer animation in his 1985 SIGGRAPH paper, Animating Rotation with Quaternion Curves.", src: "Shoemake, SIGGRAPH 1985" },
  // transforms
  { topic: "transforms", t: "Homogeneous coordinates were introduced by August Ferdinand Möbius in 1827, in Der barycentrische Calcul.", src: "https://en.wikipedia.org/wiki/Homogeneous_coordinates" },
  { topic: "transforms", t: "Lawrence Roberts used homogeneous coordinates for 3D graphics in his 1963 MIT thesis; he later managed the ARPANET program.", src: "Roberts, Machine Perception of Three-Dimensional Solids, MIT, 1963" },
  { topic: "transforms", t: "Multiplying two 4 × 4 matrices takes 64 multiplications and 48 additions; for two affine matrices, whose last row is (0, 0, 0, 1), you can skip a quarter of that.", src: "computed" },
  { topic: "transforms", t: "Translate then rotate is not rotate then translate: in the course's demo, the same two factors land the cube at (1.5, 0, 0) in one order and on an arc of radius 1.5 in the other.", src: "course text, Affine Transformations; demo trs-order" },
  // scene-graphs
  { topic: "scene-graphs", t: "Sketchpad (1963) already had master drawings and instances: change the master and every copy changes. That is the scene graph's instancing, sixty years early.", src: "Sutherland, Sketchpad thesis, 1963" },
  { topic: "scene-graphs", t: "VRML 1.0 (1994), the first 3D format for the web, was based on the file format of SGI's Open Inventor scene-graph library.", src: "https://en.wikipedia.org/wiki/VRML" },
  { topic: "scene-graphs", t: "In Unity every GameObject has exactly one Transform, and parenting one object to another is the scene graph.", src: "course text, Unity for This Course" },
  { topic: "scene-graphs", t: "A robot arm's world matrix is the product of the local matrices down its chain; in the course demo, the hand's origin at base 30° and elbow 40° is (−0.779, 1.472, 0.45).", src: "course text, Scene Graphs; HW3 rubric" },
  // viewing
  { topic: "viewing", t: "The camera obscura was described in Chinese Mohist writings around the 4th century BCE and by Ibn al-Haytham around 1021.", src: "https://en.wikipedia.org/wiki/Camera_obscura" },
  { topic: "viewing", t: "Filippo Brunelleschi demonstrated linear perspective in Florence around 1415, with a painted panel of the Baptistery viewed through a hole and a mirror.", src: "https://en.wikipedia.org/wiki/Perspective_(graphical)" },
  { topic: "viewing", t: "With near = 0.1 and far = 1000, half of an OpenGL depth buffer's range is spent between 0.1 and 0.2 units from the camera.", src: "computed: NDC depth 0 at z = 2nf/(n + f) = 0.19998" },
  { topic: "viewing", t: "OpenGL's camera looks down −z in a right-handed frame; Unity's looks down +z in a left-handed frame. The same scene needs a sign flip between them.", src: "course text, Unity for This Course §7" },
  // rasterization
  { topic: "rasterization", t: "Jack Bresenham's line algorithm, developed at IBM and published in 1965, uses integer additions only, no multiplication or division per pixel.", src: "Bresenham, IBM Systems Journal, 1965" },
  { topic: "rasterization", t: "The z-buffer was described in 1974, in Ed Catmull's Utah thesis and independently by Wolfgang Straßer.", src: "https://en.wikipedia.org/wiki/Z-buffering" },
  { topic: "rasterization", t: "Juan Pineda's 1988 paper made edge functions the basis of parallel rasterization, which is how GPUs still decide pixel coverage.", src: "Pineda, A Parallel Algorithm for Polygon Rasterization, SIGGRAPH 1988" },
  { topic: "rasterization", t: "A 4K frame has 8,294,400 pixels; at 60 frames per second that is about 498 million pixel shadings a second, before any overdraw.", src: "computed: 3840 × 2160 × 60" },
  // antialiasing
  { topic: "antialiasing", t: "Frank Crow's 1977 paper The Aliasing Problem in Computer-Generated Shaded Images named the jaggies as a sampling problem and proposed filtering as the cure.", src: "Crow, CACM 20(11), 1977" },
  { topic: "antialiasing", t: "The wagon-wheel effect, where film shows spokes turning backwards, is aliasing in time.", src: "course text, Sampling and Antialiasing" },
  { topic: "antialiasing", t: "Nyquist's sampling result dates from 1928 and Shannon's proof from 1949; graphics runs into it at every pixel.", src: "https://en.wikipedia.org/wiki/Nyquist%E2%80%93Shannon_sampling_theorem" },
  { topic: "antialiasing", t: "4× MSAA tests coverage at 4 points per pixel but runs the pixel shader once, which is why it smooths edges but not shimmering textures.", src: "course text, Sampling and Antialiasing" },
  // meshes
  { topic: "meshes", t: "For a closed triangle mesh without holes, Euler's formula V − E + F = 2 implies about twice as many triangles as vertices: the bunny's 69,451 triangles on 35,947 vertices come close.", src: "course text, Polygonal Meshes; computed" },
  { topic: "meshes", t: "Hugues Hoppe's Progressive Meshes (1996) and Garland and Heckbert's quadric error metric (1997) are still the standard ways to simplify a mesh.", src: "SIGGRAPH 1996; SIGGRAPH 1997" },
  { topic: "meshes", t: "Catmull and Clark published their subdivision surface in 1978; Pixar's Geri's Game (1997) used it for Geri's head and hands.", src: "DeRose, Kass and Truong, Subdivision Surfaces in Character Animation, SIGGRAPH 1998" },
  { topic: "meshes", t: "The Digital Michelangelo Project's raw scan of the David holds 2 billion polygons.", src: "Levoy et al., SIGGRAPH 2000" },
  // textures
  { topic: "textures", t: "Texture mapping was introduced in Ed Catmull's 1974 PhD thesis at Utah.", src: "Catmull, A Subdivision Algorithm for Computer Display of Curved Surfaces, 1974" },
  { topic: "textures", t: "“MIP” in mipmap stands for multum in parvo, Latin for “much in little”; Lance Williams introduced mipmaps in 1983.", src: "Williams, Pyramidal Parametrics, SIGGRAPH 1983" },
  { topic: "textures", t: "A full mip pyramid costs one third more memory than the base texture: 1/4 + 1/16 + 1/64 + … = 1/3.", src: "computed" },
  { topic: "textures", t: "Ken Perlin won an Academy Award for Technical Achievement in 1997 for Perlin noise, which he developed after working on Tron.", src: "https://mrl.cs.nyu.edu/~perlin/doc/oscar.html" },
  { topic: "textures", t: "Jim Blinn introduced bump mapping in 1978, two years after he and Martin Newell introduced environment mapping.", src: "Blinn, SIGGRAPH 1978; Blinn and Newell, CACM 1976" },
  // illumination
  { topic: "illumination", t: "Bui Tuong Phong described his shading and reflection model in his 1973 Utah PhD thesis and a 1975 paper. He died in 1975, at 32.", src: "https://history.siggraph.org/person/phong-bui-tuong/" },
  { topic: "illumination", t: "Henri Gouraud's smooth shading, interpolating vertex colors across a polygon, dates from 1971.", src: "Gouraud, IEEE Transactions on Computers, 1971" },
  { topic: "illumination", t: "Lambert's cosine law is from Johann Heinrich Lambert's Photometria of 1760, two centuries before the first shaded computer image.", src: "https://en.wikipedia.org/wiki/Lambert%27s_cosine_law" },
  { topic: "illumination", t: "Blinn's 1977 halfway vector replaced Phong's reflection vector in most real-time lighting because it is cheaper for a distant light and viewer.", src: "Blinn, Models of Light Reflection for Computer Synthesized Pictures, SIGGRAPH 1977" },
  { topic: "illumination", t: "In the course demo's default setup, the marked point on the sphere has N · L = 0.988 and a specular term of 0.021.", src: "course text, Local Illumination; HW5 rubric" },
  // color
  { topic: "color", t: "The CIE 1931 color space rests on color-matching experiments by W. David Wright (10 observers) and John Guild (7 observers).", src: "https://en.wikipedia.org/wiki/CIE_1931_color_space" },
  { topic: "color", t: "The sRGB byte value 128 is not half brightness: it decodes to about 0.216 of full linear light.", src: "course text, Color; computed ((128/255 + 0.055)/1.055)^2.4" },
  { topic: "color", t: "sRGB was proposed by HP and Microsoft in 1996 and standardized as IEC 61966-2-1 in 1999.", src: "https://en.wikipedia.org/wiki/SRGB" },
  { topic: "color", t: "Magenta is not in the rainbow: no single wavelength looks magenta. The eye makes it from red and blue light together.", src: "https://en.wikipedia.org/wiki/Magenta" },
  { topic: "color", t: "Newton named seven colors in the spectrum, adding orange and indigo, partly by analogy with the seven notes of the musical scale.", src: "https://en.wikipedia.org/wiki/ROYGBIV" },
  // ray-tracing
  { topic: "ray-tracing", t: "Arthur Appel cast rays from the eye to shade and shadow solids in 1968, at IBM.", src: "Appel, Some Techniques for Shading Machine Renderings of Solids, AFIPS 1968" },
  { topic: "ray-tracing", t: "Cook, Porter and Carpenter's distributed ray tracing (1984) got soft shadows, motion blur and depth of field by spreading rays over area, time and lens.", src: "Cook, Porter and Carpenter, SIGGRAPH 1984" },
  { topic: "ray-tracing", t: "NVIDIA's Turing GPUs (2018) were the first consumer GPUs with dedicated ray-tracing hardware, the RT cores.", src: "https://en.wikipedia.org/wiki/Turing_(microarchitecture)" },
  { topic: "ray-tracing", t: "Monte Carlo noise falls as one over the square root of the sample count: to halve the noise, you need four times the samples.", src: "course text, Ray Tracing and Global Illumination" },
  { topic: "ray-tracing", t: "A bounding volume hierarchy lets a ray skip most of a scene: the course text counts the boxes and triangles one ray actually tests.", src: "course text, Ray Tracing (BVH)" },
  // light-transport
  { topic: "light-transport", t: "Jim Kajiya's 1986 paper The Rendering Equation stated the equation and introduced path tracing to solve it.", src: "Kajiya, SIGGRAPH 1986" },
  { topic: "light-transport", t: "Radiosity came to graphics from heat-transfer engineering, in the same 1984 paper that introduced the Cornell box.", src: "Goral et al., SIGGRAPH 1984" },
  { topic: "light-transport", t: "Eric Veach's 1997 thesis introduced multiple importance sampling; his research on efficient Monte Carlo path tracing later earned him an Academy Scientific and Technical award.", src: "https://en.wikipedia.org/wiki/Eric_Veach" },
  { topic: "light-transport", t: "Disney's “principled” BRDF (Brent Burley, 2012) replaced dozens of material parameters with a few that artists could reason about, and most engines adopted a version of it.", src: "Burley, Physically Based Shading at Disney, SIGGRAPH 2012 course" },
  // animation
  { topic: "animation", t: "Luxo Jr. (1986) was the first 3D computer-animated film nominated for an Academy Award.", src: "https://en.wikipedia.org/wiki/Luxo_Jr." },
  { topic: "animation", t: "Toy Story (1995), the first entirely computer-animated feature, has 114,240 frames and took about 800,000 machine-hours to render.", src: "Pixar production figures, reported by Britannica and others" },
  { topic: "animation", t: "Hunger (1974), animated with Burtnyk and Wein's computer keyframe interpolation at Canada's National Research Council, was nominated for an Academy Award.", src: "https://en.wikipedia.org/wiki/Hunger_(1974_film); Carlson, Computer Graphics and Computer Animation: A Retrospective Overview, Ohio State, sec. 4.6, https://archive.org/details/ETC3236" },
  { topic: "animation", t: "Geri's Game won the 1998 Academy Award for Best Animated Short Film.", src: "https://en.wikipedia.org/wiki/Geri%27s_Game" },
  // hardware
  { topic: "hardware", t: "NVIDIA marketed the GeForce 256 (1999) as “the world's first GPU”: the first consumer chip to transform and light vertices in hardware.", src: "https://en.wikipedia.org/wiki/GeForce_256" },
  { topic: "hardware", t: "Jim Clark's Geometry Engine (1982) put the transform pipeline in VLSI and became the basis of Silicon Graphics, founded in 1981 or 1982 (sources differ).", src: "Clark, The Geometry Engine, SIGGRAPH 1982" },
  { topic: "hardware", t: "Evans & Sutherland, founded in 1968 by David Evans and Ivan Sutherland, built flight simulators whose image generators were among the first real-time 3D systems.", src: "https://en.wikipedia.org/wiki/Evans_%26_Sutherland" },
  { topic: "hardware", t: "Toy Story was rendered on a farm of 117 Sun SPARCstations.", src: "Pixar production figures, widely reported" },
  // interaction
  { topic: "interaction", t: "Douglas Engelbart showed the mouse, hypertext and live video conferencing in one 90-minute session on 9 December 1968, later called the Mother of All Demos.", src: "https://en.wikipedia.org/wiki/The_Mother_of_All_Demos" },
  { topic: "interaction", t: "Ivan Sutherland built a head-mounted display in 1968 so heavy it hung from the ceiling; it was nicknamed the Sword of Damocles.", src: "Sutherland, A Head-Mounted Three Dimensional Display, AFIPS 1968" },
  { topic: "interaction", t: "A 90 Hz VR headset gives each frame 11.1 milliseconds, for both eyes.", src: "computed: 1000 / 90" },
  { topic: "interaction", t: "Ken Shoemake's arcball (1992) turns a mouse drag into a rotation by projecting it onto a virtual sphere; the course text works one drag by hand.", src: "Shoemake, Graphics Interface 1992; course text, Interactive Systems" },
  // unity
  { topic: "unity", t: "Unity 1.0 was launched on stage at Apple's WWDC in June 2005, and the editor ran only on Mac OS X.", src: "https://en.wikipedia.org/wiki/Unity_(game_engine)" },
  { topic: "unity", t: "Unity switched from year-based version numbers to Unity 6 in 2024; the course's pinned 6000.3.11f1 is a Unity 6 release.", src: "course text, Unity for This Course §1" },
  { topic: "unity", t: "Unity's world is left-handed with y up, while this course's text and OpenGL are right-handed: a z coordinate flips sign between them.", src: "course text, Unity for This Course §7" },
  { topic: "unity", t: "transform.position.x += 1 does not compile in C#: position returns a copy of a struct. The fix is to read, modify and write back.", src: "course text, Unity for This Course §5" },
  // neural
  { topic: "neural", t: "Frank Rosenblatt demonstrated the perceptron in 1958; the Mark I Perceptron's camera was a 20 × 20 grid of photocells, a 400-pixel image.", src: "https://en.wikipedia.org/wiki/Perceptron" },
  { topic: "neural", t: "In 1966, MIT's Summer Vision Project proposed to build a significant part of a visual system over one summer. Vision took rather longer.", src: "Papert, The Summer Vision Project, MIT AI Memo 100, 1966" },
  { topic: "neural", t: "Rumelhart, Hinton and Williams popularized backpropagation in a 1986 Nature paper.", src: "Nature 323, 533 to 536 (1986)" },
  { topic: "neural", t: "In 2012 AlexNet won ImageNet with a top-5 error of 15.3 %, against 26.2 % for the next entry.", src: "Krizhevsky, Sutskever and Hinton, NeurIPS 2012" },
  { topic: "neural", t: "The transformer was introduced in 2017, in a paper titled Attention Is All You Need.", src: "Vaswani et al., arXiv:1706.03762" },
  // image-space
  { topic: "image-space", t: "A 256 × 256 RGB image is a single point in a space of 196,608 dimensions.", src: "computed: 256 × 256 × 3" },
  { topic: "image-space", t: "There are 2^784, about 10^236, black-and-white 28 × 28 images. Almost none of them look like a digit.", src: "computed: 784 × log10 2" },
  { topic: "image-space", t: "MNIST has 60,000 training and 10,000 test images of handwritten digits, each 28 × 28 pixels.", src: "LeCun, Cortes and Burges, the MNIST database" },
  { topic: "image-space", t: "JPEG (1992) compresses 8 × 8 blocks with the discrete cosine transform, the same transform the course applies to a digit.", src: "course text, The Space of Images" },
  { topic: "image-space", t: "IEEE stopped accepting papers that use the “Lena” test image from 1 April 2024, out of respect for the wishes of its subject, Lena Forsén.", src: "IEEE Computer Society announcement, March 2024" },
  // diffusion
  { topic: "diffusion", t: "Diffusion models began in a 2015 paper by Sohl-Dickstein and colleagues that borrowed its idea from non-equilibrium thermodynamics.", src: "arXiv:1503.03585" },
  { topic: "diffusion", t: "DDPM (2020) used T = 1000 noise steps, and sampling ran the network once per step.", src: "Ho, Jain and Abbeel, arXiv:2006.11239" },
  { topic: "diffusion", t: "DDIM (2021) made the sampler deterministic and cut the steps to tens, from the same trained network.", src: "Song, Meng and Ermon, arXiv:2010.02502" },
  { topic: "diffusion", t: "Stable Diffusion denoises a 64 × 64 × 4 latent for a 512 × 512 RGB image: 48 times fewer numbers than the pixels.", src: "computed: 512 × 512 × 3 / (64 × 64 × 4)" },
  // learned-scenes
  { topic: "learned-scenes", t: "The original NeRF (2020) stores a whole scene in one network of eight layers of 256 units: a few hundred thousand weights.", src: "course text, Learned Scenes" },
  { topic: "learned-scenes", t: "On the Mip-NeRF 360 benchmark, Mip-NeRF 360 trains for about 48 hours and renders at 0.06 frames per second; 3D Gaussian splatting trains in 41 minutes and renders at 134.", src: "Kerbl et al. 2023, Table 1, as quoted in the course text" },
  { topic: "learned-scenes", t: "A 3D Gaussian with degree-3 spherical harmonics has 59 numbers: 3 for position, 4 for rotation, 3 for scale, 1 for opacity, and 48 for view-dependent color.", src: "computed; Kerbl et al. 2023" },
  { topic: "learned-scenes", t: "Instant-NGP (2022) trained a NeRF in seconds with a multiresolution hash encoding and won a SIGGRAPH 2022 best paper award.", src: "https://nvlabs.github.io/instant-ngp/" },
  { topic: "learned-scenes", t: "The bonsai scene in the course's splatting demo is about 240,000 Gaussians, drawn by a rasterizer, not traced.", src: "course hub, gsplat demo" },
  // generative
  { topic: "generative", t: "Ian Goodfellow and colleagues introduced generative adversarial networks in 2014.", src: "Goodfellow et al., arXiv:1406.2661" },
  { topic: "generative", t: "Stable Diffusion's weights were released publicly in August 2022, so anyone with a gaming GPU could run a text-to-image model.", src: "https://en.wikipedia.org/wiki/Stable_Diffusion" },
  { topic: "generative", t: "DreamFusion (2022) made 3D objects from text with no 3D training data, by using a 2D image model as a critic of rendered views.", src: "Poole et al., arXiv:2209.14988" },
  { topic: "generative", t: "CLIP (2021) learned to match images and captions from 400 million image-text pairs collected from the internet.", src: "Radford et al., arXiv:2103.00020" },
  // film-games
  { topic: "film-games", t: "Tron (1982) was not considered for the visual effects Oscar; the usual story is that the Academy thought using computers was cheating, though some who were there say the branch simply did not understand it.", src: "https://www.indiewire.com/features/commentary/how-tron-changed-movies-forever-oscar-1235152775/" },
  { topic: "film-games", t: "Ed Catmull, Loren Carpenter and Rob Cook received an Academy Award of Merit for RenderMan, the first Oscar statuette given for software.", src: "https://renderman.pixar.com/about" },
  { topic: "film-games", t: "Doom (1993) sorted its walls with a binary space partitioning tree, a 1980 graphics research idea, to draw them fast on a PC.", src: "https://en.wikipedia.org/wiki/Doom_engine" },
  { topic: "film-games", t: "Quake III Arena (1999) contains the “fast inverse square root” with the magic constant 0x5f3759df, used to normalize vectors for lighting.", src: "https://en.wikipedia.org/wiki/Fast_inverse_square_root" },
  { topic: "film-games", t: "Wolfenstein 3D (1992) drew its walls by casting one ray per screen column, a 2D ray tracer running on a 1992 PC.", src: "https://en.wikipedia.org/wiki/Ray_casting" },
  { topic: "curves", t: "Paul de Casteljau devised his curve algorithm at Citroën in 1959, in internal reports the company kept secret; Pierre Bézier published the same curves from Renault, and they carry his name.", src: "Farin, A History of Curves and Surfaces in CAGD, 2002" },
  { topic: "shaders", t: "Pat Hanrahan and Jim Lawson's 1990 shading language for RenderMan made a surface's appearance a program; programmable shaders reached consumer graphics cards about a decade later.", src: "Hanrahan and Lawson, A Language for Shading and Lighting Calculations, SIGGRAPH 1990" },
  { topic: "webgl", t: "The Khronos Group released the WebGL 1.0 specification in March 2011, bringing GPU rendering to the browser without plug-ins.", src: "Khronos Group, WebGL 1.0 specification, 2011" },
  { topic: "webgl", t: "GLSL, the OpenGL Shading Language, arrived with OpenGL 2.0 in 2004; WebGL shaders are written in its OpenGL ES dialect.", src: "Khronos Group, OpenGL 2.0 specification, 2004" },
];

export const QUOTES = [
  { q: "The ultimate display would, of course, be a room within which the computer can control the existence of matter.", who: "Ivan Sutherland", src: "“The Ultimate Display,” IFIP Congress, 1965" },
  { q: "What I cannot create, I do not understand.", who: "Richard Feynman", src: "written on his blackboard, 1988" },
  { q: "Know how to solve every problem that has been solved.", who: "Richard Feynman", src: "written on the same blackboard, 1988" },
  { q: "The first principle is that you must not fool yourself, and you are the easiest person to fool.", who: "Richard Feynman", src: "“Cargo Cult Science,” Caltech commencement address, 1974" },
  { q: "The purpose of computing is insight, not numbers.", who: "Richard Hamming", src: "Numerical Methods for Scientists and Engineers, 1962" },
  { q: "In science, if you know what you are doing, you should not be doing it. In engineering, if you do not know what you are doing, you should not be doing it.", who: "Richard Hamming", src: "The Art of Doing Science and Engineering, 1997" },
  { q: "All models are wrong, but some are useful.", who: "George Box", src: "“Robustness in the Strategy of Scientific Model Building,” 1979" },
  { q: "A pixel is not a little square.", who: "Alvy Ray Smith", src: "Microsoft Technical Memo 6, 1995" },
  { q: "Premature optimization is the root of all evil.", who: "Donald Knuth", src: "“Structured Programming with go to Statements,” 1974" },
  { q: "Beware of bugs in the above code; I have only proved it correct, not tried it.", who: "Donald Knuth", src: "memo to Peter van Emde Boas, 1977" },
  { q: "Science is what we understand well enough to explain to a computer. Art is everything else we do.", who: "Donald Knuth", src: "foreword to A = B, 1996" },
  { q: "The best way to predict the future is to invent it.", who: "Alan Kay", src: "Xerox PARC, 1971" },
  { q: "Point of view is worth 80 IQ points.", who: "Alan Kay", src: "Creative Think seminar, 1982 (recorded by Andy Hertzfeld)" },
  { q: "The art challenges the technology, and the technology inspires the art.", who: "John Lasseter", src: "attributed; quoted by Pixar" },
  { q: "The biggest lesson that can be read from 70 years of AI research is that general methods that leverage computation are ultimately the most effective, and by a large margin.", who: "Rich Sutton", src: "“The Bitter Lesson,” 2019" },
  { q: "Any sufficiently advanced technology is indistinguishable from magic.", who: "Arthur C. Clarke", src: "Profiles of the Future, 1973 edition" },
  { q: "Everyone knows that debugging is twice as hard as writing a program in the first place. So if you're as clever as you can be when you write it, how will you ever debug it?", who: "Brian Kernighan and P. J. Plauger", src: "The Elements of Programming Style, 2nd ed., 1978" },
  { q: "Adding manpower to a late software project makes it later.", who: "Fred Brooks", src: "The Mythical Man-Month, 1975" },
  { q: "Program testing can be used to show the presence of bugs, but never to show their absence!", who: "Edsger Dijkstra", src: "Notes on Structured Programming, 1970" },
  { q: "Simplicity is prerequisite for reliability.", who: "Edsger Dijkstra", src: "EWD498, 1975" },
  { q: "A language that doesn't affect the way you think about programming, is not worth knowing.", who: "Alan Perlis", src: "“Epigrams on Programming,” SIGPLAN Notices, 1982" },
  { q: "Simplicity does not precede complexity, but follows it.", who: "Alan Perlis", src: "“Epigrams on Programming,” SIGPLAN Notices, 1982" },
  { q: "There are two ways of constructing a software design: One way is to make it so simple that there are obviously no deficiencies, and the other way is to make it so complicated that there are no obvious deficiencies.", who: "C. A. R. Hoare", src: "“The Emperor's Old Clothes,” Turing Award lecture, 1980" },
  { q: "Data dominates. If you've chosen the right data structures and organized things well, the algorithms will almost always be self-evident.", who: "Rob Pike", src: "“Notes on Programming in C,” 1989" },
  { q: "If you can't solve a problem, then there is an easier problem you can solve: find it.", who: "George Pólya", src: "How to Solve It, 2nd ed., 1957" },
  { q: "With four parameters I can fit an elephant, and with five I can make him wiggle his trunk.", who: "John von Neumann", src: "as recalled by Enrico Fermi to Freeman Dyson, Nature 427, 2004" },
  { q: "If you wish to make an apple pie from scratch, you must first invent the universe.", who: "Carl Sagan", src: "Cosmos, 1980" },
  { q: "When you can measure what you are speaking about, and express it in numbers, you know something about it.", who: "Lord Kelvin", src: "“Electrical Units of Measurement,” lecture, 1883" },
  { q: "Perfection is achieved, not when there is nothing more to add, but when there is nothing left to take away.", who: "Antoine de Saint-Exupéry", src: "Terre des Hommes, 1939 (translated)" },
  { q: "It is comparatively easy to make computers exhibit adult level performance on intelligence tests or playing checkers, and difficult or impossible to give them the skills of a one-year-old when it comes to perception and mobility.", who: "Hans Moravec", src: "Mind Children, 1988" },
  { q: "If intelligence is a cake, the bulk of the cake is unsupervised learning, the icing on the cake is supervised learning, and the cherry on the cake is reinforcement learning.", who: "Yann LeCun", src: "NIPS keynote, 2016" },
  { q: "Neural networks are not just another classifier, they represent the beginning of a fundamental shift in how we develop software.", who: "Andrej Karpathy", src: "“Software 2.0,” 2017" },
  { q: "When in doubt, use brute force.", who: "Ken Thompson", src: "attributed" },
  { q: "All problems in computer science can be solved by another level of indirection.", who: "David Wheeler", src: "attributed, as quoted by Butler Lampson" },
  { q: "There are only two hard things in Computer Science: cache invalidation and naming things.", who: "Phil Karlton", src: "attributed" },
  { q: "There is nothing worse than a sharp image of a fuzzy concept.", who: "Ansel Adams", src: "attributed" },
  { q: "Simple things should be simple, complex things should be possible.", who: "Alan Kay", src: "attributed" },
  { q: "Write programs that do one thing and do it well.", who: "Doug McIlroy", src: "the Unix philosophy, as summarized by Peter Salus, 1994" },
  { q: "It's not so much that Tron was ahead of its time, it's that everyone else was late.", who: "Steven Lisberger", src: "on Tron's Oscar snub, as quoted by IndieWire" },
  { q: "How about sending me a fourth gimbal for Christmas?", who: "Michael Collins", src: "Apollo 11 air-to-ground transcript, 1969" },
];

// xkcd by Randall Munroe, https://xkcd.com, CC BY-NC 2.5; titles and alt text from each strip's
// info.0.json. Images are unmodified copies in media/comics/ (see media/comics/CREDITS.md).
export const COMICS = [
  { num: 1425, title: "Tasks", alt: "In the 60s, Marvin Minsky assigned a couple of undergrads to spend the summer programming a computer to use a camera to identify objects in a scene. He figured they'd have the problem solved by the end of the summer. Half a century later, we're still working on it.",
    img: "media/comics/xkcd-1425.png", topic: "neural", why: "Why vision was hard for fifty years, and what learned models changed." },
  { num: 1838, title: "Machine Learning", alt: "The pile gets soaked with data and starts to get mushy over time, so it's technically recurrent.",
    img: "media/comics/xkcd-1838.png", topic: "neural", why: "Training by stirring: gradient descent, seen from outside." },
  { num: 2173, title: "Trained a Neural Net", alt: "It also works for anything you teach someone else to do. \"Oh yeah, I trained a pair of neural nets, Emily and Kevin, to respond to support tickets.\"",
    img: "media/comics/xkcd-2173.png", topic: "neural", why: "What “training a network” does and does not mean." },
  { num: 2048, title: "Curve-Fitting", alt: "Cauchy-Lorentz: \"Something alarmingly mathematical is happening, and you should probably pause to Google my name and check what field I originally worked in.\"",
    img: "media/comics/xkcd-2048.png", topic: "neural", why: "Every model is a curve fit; choose the curve with care." },
  { num: 2117, title: "Differentiation and Integration", alt: "\"Symbolic integration\" is when you theatrically go through the motions of finding integrals, but the actual result you get doesn't matter because it's purely symbolic.",
    img: "media/comics/xkcd-2117.png", topic: "light-transport", why: "Why the rendering equation is solved by sampling, not by hand." },
  { num: 1416, title: "Pixels", alt: "It's turtles all the way down.",
    img: "media/comics/xkcd-1416.png", topic: "rasterization", why: "An infinitely zoomable image (interactive on xkcd.com): the opposite of a pixel grid." },
  { num: 1205, title: "Is It Worth the Time?", alt: "Don't forget the time you spend finding the chart to look up what you save. And the time spent reading this reminder about the time spent. And the time trying to figure out if either of those actually make sense. Remember, every second counts toward your life total, including these right now.",
    img: "media/comics/xkcd-1205.png", topic: "hardware", why: "Budgets: when a speedup pays for the effort, the frame-budget question in table form." },
  { num: 303, title: "Compiling", alt: "'Are you stealing those LCDs?' 'Yeah, but I'm doing it while my code compiles.'",
    img: "media/comics/xkcd-303.png", topic: "unity", why: "Unity's script recompile, shader compile and asset import, in one picture." },
  { num: 2347, title: "Dependency", alt: "Someday ImageMagick will finally break for good and we'll have a long period of scrambling as we try to reassemble civilization from the rubble.",
    img: "media/comics/xkcd-2347.png", topic: "interaction", why: "Every engine and demo stands on libraries you never see." },
  { num: 1597, title: "Git", alt: "If that doesn't fix it, git.txt contains the phone number of a friend of mine who understands git. Just wait through a few minutes of 'It's really pretty simple, just think of branches as...' and eventually you'll learn the commands that will fix everything.",
    img: "media/comics/xkcd-1597.png", topic: "unity", why: "Version control for homework projects, honestly described." },
  { num: 612, title: "Estimation", alt: "They could say \"the connection is probably lost,\" but it's more fun to do naive time-averaging to give you hope that if you wait around for 1,163 hours, it will finally finish.",
    img: "media/comics/xkcd-612.png", topic: "interaction", why: "Progress bars and latency: estimates the user sees." },
];
