// GENERATED by tools/test-homework.mjs --write from the reference solutions. Do not edit.
// The numbers a correct HW1 reproduces, the same as the homework page and the WebGL runner.
using UnityEngine;

namespace CSS551.HW01
{
    public struct Check
    {
        public string Id, Label; public int Points; public double Tol; public double[] Want;
        public Check(string id, string label, int points, double tol, double[] want) { Id = id; Label = label; Points = points; Tol = tol; Want = want; }
    }

    public static class Expected
    {
        public static readonly Check[] Checks = {
            new Check("step60", "advance: position after 1 s at 60 frames per second", 10, 0.0001, new double[] { 3.0, 0.0, 0.0 }),
            new Check("step20", "advance: position after 1 s at 20 frames per second", 10, 0.0001, new double[] { 3.0, 0.0, 0.0 }),
            new Check("trs", "trsMatrix(t, 30, 2): the 16 entries, column-major", 25, 0.001, new double[] { 1.73205080757, 0.0, -1.0, 0.0, 0.0, 2.0, 0.0, 0.0, 1.0, 0.0, 1.73205080757, 0.0, 2.0, 0.5, -1.0, 1.0 }),
            new Check("trsPoint", "trsMatrix applied to the point (1, 0, 0)", 10, 0.001, new double[] { 3.73205080757, 0.5, -2.0 }),
            new Check("aimZ", "orientBasis: forward axis z (toward the target)", 15, 0.001, new double[] { -0.588348405415, 0.196116135138, -0.784464540553 }),
            new Check("aimX", "orientBasis: right axis x", 15, 0.001, new double[] { -0.8, 0.0, 0.6 }),
            new Check("aimY", "orientBasis: up axis y", 15, 0.001, new double[] { 0.117669681083, 0.980580675691, 0.156892908111 }),
        };
    }
}
