// GENERATED by tools/test-homework.mjs --write. Do not edit.
// The published inputs of HW1 (the same as lib/skeletons/checks.js).
using UnityEngine;

namespace CSS551.HW01
{
    public static class Inputs
    {
        public static readonly float speed = 3f;
        public static readonly Vector3 trs_t = new Vector3(2f, 0.5f, -1f);
        public static readonly float trs_ry = 30f;
        public static readonly float trs_s = 2f;
        public static readonly Vector3 point = new Vector3(1f, 0f, 0f);
        public static readonly Vector3 aim_pos = new Vector3(1f, 0.5f, 2f);
        public static readonly Vector3 aim_target = new Vector3(-2f, 1.5f, -2f);
        public static readonly Vector3 aim_up = new Vector3(0f, 1f, 0f);
    }
}
