// GENERATED by tools/test-homework.mjs --write from the reference solutions. Do not edit.
// The numbers a correct HW2 reproduces, the same as the homework page and the WebGL runner.
using UnityEngine;

namespace CSS551.HW02
{
    public struct Check
    {
        public string Id, Label; public int Points; public double Tol; public double[] Want;
        public Check(string id, string label, int points, double tol, double[] want) { Id = id; Label = label; Points = points; Tol = tol; Want = want; }
    }

    public static class Expected
    {
        public static readonly Check[] Checks = {
            new Check("march", "EX1 marchStep: one step toward (4, 0, 3)", 8, 0.001, new double[] { 0.8, 0.0, 0.6 }),
            new Check("line", "EX1 lineFrame: midpoint, direction, length", 8, 0.001, new double[] { 2.5, 2.0, 0.0, 0.6, 0.8, 0.0, 5.0 }),
            new Check("plane", "EX2 planeFromPoint: unit normal n and D", 8, 0.001, new double[] { 0.333333333333, 0.666666666667, 0.666666666667, 0.333333333333 }),
            new Check("side", "EX3 signedDistance for P = (4, 1, 0) and P2 = (-1, 0, 0)", 8, 0.001, new double[] { 1.66666666667, -0.666666666667 }),
            new Check("shadow", "EX4 shadowOnPlane of P", 10, 0.001, new double[] { 3.44444444444, -0.111111111111, -1.11111111111 }),
            new Check("hit", "EX5 linePlaneHit for the segment P to P2", 10, 0.001, new double[] { 0.428571428571, 0.285714285714, 0.0 }),
            new Check("reflect", "EX5 reflect: the unit direction P to P2 reflected about n", 10, 0.001, new double[] { -0.675511132143, 0.414022951958, 0.610139087097 }),
            new Check("cylIn", "EX6 projectToCylinder: (1.2, 0.6, -0.9), point and inside", 8, 0.001, new double[] { 0.4, 0.6, -0.3, 1.0 }),
            new Check("cylOut", "EX6 projectToCylinder: (0.9, 1.4, 0.4), point and inside", 6, 0.001, new double[] { 0.45690577431, 1.4, 0.203069233027, 0.0 }),
            new Check("rodrigues", "rotateAxisAngle: (1, 0.6, 0.3) by 30° about y", 10, 0.001, new double[] { 1.01602540378, 0.6, -0.240192378865 }),
            new Check("quat", "quatFromAxisAngle: 30° about y, as [x, y, z, w]", 7, 0.001, new double[] { 0.0, 0.258819045103, 0.0, 0.965925826289 }),
            new Check("quatRot", "quatRotate: the same rotation applied by the quaternion", 7, 0.001, new double[] { 1.01602540378, 0.6, -0.240192378865 }),
        };
    }
}
