// GENERATED by tools/test-homework.mjs --write. Do not edit.
// The published inputs of HW2 (the same as lib/skeletons/checks.js).
using UnityEngine;

namespace CSS551.HW02
{
    public static class Inputs
    {
        public static readonly Vector3 march_p = new Vector3(0f, 0f, 0f);
        public static readonly Vector3 march_from = new Vector3(0f, 0f, 0f);
        public static readonly Vector3 march_to = new Vector3(4f, 0f, 3f);
        public static readonly float march_speed = 2f;
        public static readonly float march_dt = 0.5f;
        public static readonly Vector3 line_p1 = new Vector3(1f, 0f, 0f);
        public static readonly Vector3 line_p2 = new Vector3(4f, 4f, 0f);
        public static readonly Vector3 plane_m = new Vector3(1f, 2f, 2f);
        public static readonly Vector3 plane_q = new Vector3(1f, 0f, 0f);
        public static readonly Vector3 P = new Vector3(4f, 1f, 0f);
        public static readonly Vector3 P2 = new Vector3(-1f, 0f, 0f);
        public static readonly Vector3 cyl_c = new Vector3(0f, 0f, 0f);
        public static readonly Vector3 cyl_axis = new Vector3(0f, 1f, 0f);
        public static readonly float cyl_radius = 0.5f;
        public static readonly float cyl_halfHeight = 1f;
        public static readonly Vector3 cyl_inside = new Vector3(1.2f, 0.6f, -0.9f);
        public static readonly Vector3 cyl_outside = new Vector3(0.9f, 1.4f, 0.4f);
        public static readonly Vector3 rot_v = new Vector3(1f, 0.6f, 0.3f);
        public static readonly Vector3 rot_axis = new Vector3(0f, 1f, 0f);
        public static readonly float rot_deg = 30f;
    }
}
