// GENERATED by tools/test-homework.mjs --write from the reference solutions. Do not edit.
// The numbers a correct HW5 reproduces, the same as the homework page and the WebGL runner.
using UnityEngine;

namespace CSS551.HW05
{
    public struct Check
    {
        public string Id, Label; public int Points; public double Tol; public double[] Want;
        public Check(string id, string label, int points, double tol, double[] want) { Id = id; Label = label; Points = points; Tol = tol; Want = want; }
    }

    public static class Expected
    {
        public static readonly Check[] Checks = {
            new Check("indices", "gridMesh(2, 1.5, 0.4): the eight index triples", 12, 0.0, new double[] { 0.0, 3.0, 1.0, 1.0, 3.0, 4.0, 1.0, 4.0, 2.0, 2.0, 4.0, 5.0, 3.0, 6.0, 4.0, 4.0, 6.0, 7.0, 4.0, 7.0, 5.0, 5.0, 7.0, 8.0 }),
            new Check("center", "gridMesh: position of the lifted center vertex (vertex 4 when n = 2)", 4, 0.000001, new double[] { 0.0, 0.4, 0.0 }),
            new Check("face1", "faceNormal of triangle 1 (vertices 1, 3, 4 when n = 2), unnormalized", 10, 0.001, new double[] { -0.6, 2.25, -0.6 }),
            new Check("vn1", "vertexNormals: vertex 1", 12, 0.001, new double[] { -0.0871834280054, 0.98081356506, -0.174366856011 }),
            new Check("vn4", "vertexNormals: the center vertex", 6, 0.001, new double[] { 0.0, 1.0, 0.0 }),
            new Check("uvDef", "uvPlacement at the defaults (0, 0, 0°, tile 2): 9 entries", 10, 0.001, new double[] { 2.0, 0.0, 0.0, 0.0, 2.0, 0.0, -0.5, -0.5, 1.0 }),
            new Check("uvAll", "uvPlacement(0.25, 0, 45°, 2): 9 entries", 14, 0.001, new double[] { 1.41421356237, -1.41421356237, 0.0, 1.41421356237, 1.41421356237, 0.0, -0.664213562373, 0.5, 1.0 }),
            new Check("NL", "phong at the marked point: N·L and diffuse", 10, 0.001, new double[] { 0.988348511442, 0.988348511442 }),
            new Check("spec", "phong: R·V and the Phong specular (R·V)^30", 12, 0.001, new double[] { 0.878826139089, 0.0207533864062 }),
            new Check("blinn", "phong: H·N and the Blinn specular (H·N)^30", 10, 0.001, new double[] { 0.968875796778, 0.387296178252 }),
        };
    }
}
