// GENERATED by tools/test-homework.mjs --write. Do not edit.
// The published inputs of HW5 (the same as lib/skeletons/checks.js).
using UnityEngine;

namespace CSS551.HW05
{
    public static class Inputs
    {
        public static readonly float grid_n = 2f;
        public static readonly float grid_half = 1.5f;
        public static readonly float grid_lift = 0.4f;
        public static readonly float[] uvDefaults = { 0f, 0f, 0f, 2f };
        public static readonly float[] uvAll = { 0.25f, 0f, 45f, 2f };
        public static readonly Vector3 shade_N = new Vector3(0.57735f, 0.57735f, 0.57735f);
        public static readonly Vector3 shade_P = new Vector3(0.692820323027551f, 0.692820323027551f, 0.692820323027551f);
        public static readonly Vector3 shade_light = new Vector3(1.8371173070873839f, 1.4999999999999998f, 1.8371173070873834f);
        public static readonly Vector3 shade_eye = new Vector3(3f, 3f, 6f);
        public static readonly float shade_shine = 30f;
    }
}
