// GENERATED by tools/test-homework.mjs --write from the reference solutions. Do not edit.
// The numbers a correct HW3 reproduces, the same as the homework page and the WebGL runner.
using UnityEngine;

namespace CSS551.HW03
{
    public struct Check
    {
        public string Id, Label; public int Points; public double Tol; public double[] Want;
        public Check(string id, string label, int points, double tol, double[] want) { Id = id; Label = label; Points = points; Tol = tol; Want = want; }
    }

    public static class Expected
    {
        public static readonly Check[] Checks = {
            new Check("ts", "T(3,0,0) · S(2,1,1): translation column", 8, 0.000001, new double[] { 3.0, 0.0, 0.0 }),
            new Check("st", "S(2,1,1) · T(3,0,0): translation column", 8, 0.000001, new double[] { 6.0, 0.0, 0.0 }),
            new Check("pivot", "pivotRotateY((1.5, 0, 0), 90): translation column (I − R)p", 12, 0.001, new double[] { 1.5, 0.0, 1.5 }),
            new Check("pivotPt", "pivotRotateY: the image of the point one unit past the pivot in x", 6, 0.001, new double[] { 1.5, 0.0, -1.0 }),
            new Check("rigidInv", "rigidInverse of T(0,0,−1) · R_y(90): all 16 entries", 14, 0.001, new double[] { 6.12323399574e-17, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, -1.0, 0.0, 6.12323399574e-17, 0.0, -1.0, 0.0, 6.12323399574e-17, 1.0 }),
            new Check("wHand", "worldMatrices at baseRy 30, armBend 40: W_hand, 16 entries", 20, 0.002, new double[] { 0.663413948169, 0.642787609687, -0.383022221559, 0.0, -0.556670399226, 0.766044443119, 0.321393804843, 0.0, 0.5, 0.0, 0.866025403784, 0.0, -0.779338558917, 1.47246222037, 0.449951326781, 1.0 }),
            new Check("handPos", "hand origin in world space", 8, 0.002, new double[] { -0.779338558917, 1.47246222037, 0.449951326781 }),
            new Check("armPos", "arm origin in world space", 8, 0.002, new double[] { -0.389669279458, 0.936231110183, 0.22497566339 }),
            new Check("toLocal", "worldToLocal: world point (0, 1, 0) in the hand frame", 16, 0.002, new double[] { 0.385672565812, -0.940373334129, 0.0 }),
        };
    }
}
