// GENERATED by tools/test-homework.mjs --write. Do not edit.
// The published inputs of HW3 (the same as lib/skeletons/checks.js).
using UnityEngine;

namespace CSS551.HW03
{
    public static class Inputs
    {
        public static readonly Vector3 order_s = new Vector3(2f, 1f, 1f);
        public static readonly Vector3 order_t = new Vector3(3f, 0f, 0f);
        public static readonly Vector3 pivot_p = new Vector3(1.5f, 0f, 0f);
        public static readonly float pivot_deg = 90f;
        public static readonly float rigid_ry = 90f;
        public static readonly Vector3 rigid_t = new Vector3(0f, 0f, -1f);
        public static readonly float pose_baseRy = 30f;
        public static readonly float pose_armBend = 40f;
        public static readonly float pose_handRy = 0f;
        public static readonly float pose_armT = 0f;
        public static readonly Vector3 worldPoint = new Vector3(0f, 1f, 0f);
    }
}
